### PR TITLE
Add a `--hard-abi-lock` option to lock to an exact ruby version

### PR DESCRIPTION
**Pull request by underscorebrody**

### CODE REVIEW

**Comment by luislavena** [comment]
Hello @underscorebrody, thank you for your contribution.

Would you mind explaining a little bit specific need behind this change? While you mention _hard lock_, by using `~>` when comparing versions, it will accept any newer patchlevel version:

```
require "rbconfig"
current_xyzp = RbConfig::CONFIG.values_at("MAJOR", "MINOR", "TEENY", "PATCHLEVEL").join(".") # => "2.6.5.114"
v1 = Gem::Version.new(current_xyzp) # => #<Gem::Version "2.6.5.114">
v2 = Gem::Version.new "2.6.5.250" # => #<Gem::Version "2.6.5.250">

r1 = Gem::Requirement.new "~> #{current_xyzp}"
# => #<Gem::Requirement:0x00005637d17c5308 @requirements=[["~>", #<Gem::Version "2.6.5.114">]]>

r1.satisfied_by? v1 # => true
r1.satisfied_by? v2 # => true
```

Thank you once again for your interest and contribution. Looking forward your comments.

Cheers.

**Comment by underscorebrody** [comment]
You're completely right, and the actual desired behavior here is to allow any patch level at the specified ruby version.

The reason for this change (and _please_ let me know if you have another solution in mind, as this may be hacky) is mainly around portability for gems compiled within environments that use RVM. RVM has a behavior where it changes the `libruby.so` shared object location to one that has the `major.minor.teeny` ruby version in the directory structure. So, for example, on ruby 2.6.5.xxx it would try to find libruby.so at `/usr/local/rvm/rubies/ruby-2.6.5/lib/libruby.so.2.6`. This causes any gems that are built within that environment to only be portable for other environments that use RVM and ruby 2.6.5. The change here allows us to at least be aware at `bundle` time if gems compiled in an incompatible ruby version are being pulled in (though doesn't address non-RVM environments, obviously). 

This is all in the interest of compiling gems with native extensions and then caching the platform-specific builds via a https://github.com/geminabox/geminabox instance to speed up future builds.

**Comment by luislavena** [comment]
Hello @underscorebrody, thanks for your patience.

Thank you for explaining a bit further your needs on this. I've been thinking a bit further in the UX of this, so bear with me with the following scenarios:

```console
# default behavior: locks to Ruby's ABI (MAJOR.MINOR)
$ gem compile mygem.gem
$ gem compile mygem.gem --abi-lock=default

# disable entire ABI locking
$ gem compile mygem.gem --no-abi-lock

# use more strict ABI locking (MAJOR.MINOR.TEENY.0)
$ gem compile mygem.gem --abi-lock=strict
```

What do you think?

**Comment by luislavena** [comment]
Hello @underscorebrody, closed this in favor of #52 which addressed your need and normalized the usage of `--abi-lock` and `-no-abi-lock`.

Cheers.

**Comment by luislavena** [comment]
Hello @underscorebrody, recently I remember that an issue similar to this was reported, see #1 

One recommendation to avoid the strict ABI will be to compile the versions of Ruby using `--enable-load-relative` configure option. 

Hope that helps.

Cheers.

**Pull request closed without merging**
