### PR TITLE
please update README.md to highlight potential windows error

### PR DESCRIPTION
**Pull request by cixelsyd**
I have added a common windows failure scenario, as well as the solution, to your README.
Thanks for the good work!

steve

### CODE REVIEW

**Comment by luislavena** [comment]
@cixelsyd thank you for the patch, however proper DevKit installation (as RubyGems plugin) shouldn't require you to load `devkitvars.bat`

Is that the case? Please confirm so perhaps a better hook can be added to gem-compiler so no extra command is required.

Thank you.

**Comment by luislavena** [comment]
@cixelsyd can you confirm the DevKit has been properly installed? As mentioned it shouldn't be required to load it independently since is a RubyGems plugin and that is automatically enabled when using RubyGems.

Thank you.

**Comment by cixelsyd** [comment]
Hi Luis! I've installed ruby and ruby devkit before, and was reasonably sure I didn't make an error here.  Let me try to uninstall and re-install them and see what happens.

**Comment by luislavena** [comment]
Hello @cixelsyd, I was able to confirm that gem-compiler was not able to compile gems on Windows even when DevKit was present.

Instead of document yet another thing in the README, decided to fix it in #21, which just merged.

Will be part of next release.

Thank you for your patience and bring this issue to my attention (and sorry for the delay on getting this solved).

Cheers.

**Comment by cixelsyd** [comment]
Great, Luis!

Thank you!



On Sat, Apr 23, 2016 at 8:35 PM, Luis Lavena <notifications@github.com>
wrote:

> Hello @cixelsyd <https://github.com/cixelsyd>, I was able to confirm that
> gem-compiler was not able to compile gems on Windows even when DevKit was
> present.
>
> Instead of document yet another thing in the README, decided to fix it in
> #21 <https://github.com/luislavena/gem-compiler/pull/21>, which just
> merged.
>
> Will be part of next release.
>
> Thank you for your patience and bring this issue to my attention (and
> sorry for the delay on getting this solved).
>
> Cheers.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/luislavena/gem-compiler/pull/18#issuecomment-213858061>
>



-- 
http://linkedin.com/in/cixelsydego

(508) 372-0005 (cell)

**Pull request closed without merging**
